# paths:
repo_path: Multilingual_NER/
utils_path: python/utils/

### NOTE: these are all specified relative to the location of main.py
# data paths:
## en data:
conll_path: '../data/en/CONLL2003/'
ee_path: '../data/en/emerging_entities_17/'
en_combined_path: '../data/en/combined/'
## ru data:
ru_data_path: "../data/ru/factRuEval-2016/"

# paths for model training and testing:
train_data_path: "../data/en/combined/train_combined_std.txt"
dev_data_path: "../data/en/combined/dev_combined_std.txt"
test_data_path: "../data/en/combined/test_combined_std.txt"
